SYSTEM:
    DEBUG: False
DATA:
    REFRESH: False
    SAVE_PROCESSED_TRAIN: True
EVAL:
    SAVE_PREDS: True
    SUBMIT_PREDS: False
    CHUNK_SIZE: 1000000
CV:
    VAL_START: 206
    VAL_END: 210
    VAL_N_ERAS: 4
    GAP: 0
    TRAIN_START: 0
    TRAIN_STOP: null